spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app_security_db?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    
  jpa:
    open-in-view: true
    show-sql: true
  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        

#jwt:
#  key: 949U48i38ZDrP9urxJ8JBB5amz337cRP7/1iznFkg6U=

keystore:
  password: dave123
  privateKey: daveappsec.jks
  alias: daveappsec